cmds_marek = {"Random JKG quote; special thanks to Anton:":["```/jkg```", False],
              "Search for specific JKG quote:":["```/jkg [search query]```", False],
              "Clash of Clans commands help:":["```/coc help```", False],
              "Spotify commands help:":["```/spotify help```", False],
              "User profile commands help:":["```/profile help```", False],
              "Guess the capital of a given country:":["```/GeoGuesser```", False],
              '"Now playing" shows your current music streaming activity and lets other people rate it':["```/np```", False],
              "System info of bot's host machine:":["```/system```", False],
              "Google Cloud Platform logs:":["```/GoogleCloud```", False],
              "Send feedback or report an issue:":["```/feedback```", False]}

cmds_coc = {"Info on the clan members:":["```/coc members```", False],
            "Info on the current clan war:":["```/coc cw```", False],
            "List of members who haven't attacked in the current clan war yet:":["```/coc attacks```", False],
            "Clash of Clans loot:":["```/coc loot```", False],
            "Clash village info:":["```/coc```", False],
            "Add Clash village to Discord user profile:":["```/coc add 2VQUVJYRO```Of course, use your own village tag.", False],
            "Important:":["Add clan tag (without '#') after clan commands to target a specific clan. Leave empty to target the DaBaByClan by default.", False]}

cmds_spotify = {"Skip current track:":["```/spotify skip```", False],
                "Pause current track:":["```/spotify pause```", False],
                "Play current track:":["```/spotify play```", False],
                "Top songs collage:":["```/spotify collage [side length] [time period]```", False],
                "Get full res album cover of given spotify song url:":["```/spotify cover [Spotify song URL or ID]```", False]}

cmds_profile = {"See your collected data:":["```/profile```", False],
                "Add last.fm user to Discord profile:":["```/profile lastfm xelemir```Of course, use your own last.fm user name.", False],
                "See your GeoGuesser stats:":["```/profile geo```", False],
                "Delete your collected data:":["```/profile delete data```", False],
                "Note:":['You can use "/user" or "/userprofile" as an alias for all "/profile" commands', False]}

charli_emojis = {"TODO_ALBUM_NAME1": "<:CUSTOM_EMOJI_NAME1:CUSTOM_EMOJI_ID1>",
                 "TODO_ALBUM_NAME2": "<:CUSTOM_EMOJI_NAME2:CUSTOM_EMOJI_ID2>",
                 "TODO_ALBUM_NAME3": "<:CUSTOM_EMOJI_NAME3:CUSTOM_EMOJI_ID3>",
                 "TODO_ALBUM_NAME4": "<:CUSTOM_EMOJI_NAME4:CUSTOM_EMOJI_ID4>"}

#Charli keywords
charliE = []
charliE.extend(("Charlie", "CharliE", "charlie", "CHARLIE"))

# DaBaby keyword filter
dababy = []
dababy.extend(("DaBaby", "dababy", "DABABY", "Dababy"))

# Amogus keywords filter
amogus = []
amogus.extend(("AMOGUS", "Amogus", "amogus", "aMOGUS"))

# Amongus keyword filter
amongus = []
amongus.extend(("Amongus", "AMONGUS", "amongus", "Among Us", "among us", "Among us", "AMONG US"))

# filter offensive words
filter_list = []
filter_list.extend(("TODO_OFFENSIVE_WORD1", "TODO_OFFENSIVE_WORD1_SPELLED_DIFFERENTLY"))
filter_list.extend(("TODO_OFFENSIVE_WORD2", "TODO_OFFENSIVE_WORD2_SPELLED_DIFFERENTLY"))

# General images
coc_img = "TODO_CLASH_OF_CLANS_LOGO.png"
marek_img = "TODO_MAREK.png"
locked_img = "TODO_LOCKED_LOCK.png"
spotify_img = "https://storage.googleapis.com/pr-newsroom-wp/1/2018/11/Spotify_Logo_RGB_Green.png"
error_img = "TODO_ERROR.png"
gcp_img = "TODO_GCP_LOGO.png"

# Images of people
TODO_PERSON1 = ["TODO_IMAGE_URL1_PERSON1",
       "TODO_IMAGE_URL2_PERSON1"]

TODO_PERSON2 = ["TODO_IMAGE_URL1_PERSON2",
          "TODO_IMAGE_URL2_PERSON2"]

TODO_PERSON3 = ["TODO_IMAGE_URL1_PERSON3",
         "TODO_IMAGE_URL2_PERSON3",
         "TODO_IMAGE_URL3_PERSON3",
         "TODO_IMAGE_URL4_PERSON3"]

TODO_PERSON4 = "TODO_IMAGE_URL_PERSON4"

# Filter quotes for words. Quotes containing these words can only be used by members that are part of a trusted server guild.
jkg_filter = ["TODO_FILTER_WORD1", "TODO_FILTER_WORD2", "TODO_FILTER_WORD3"]

jkg_quotes = {}
jkg_quotes["TODO_FUNNY_QUOTE1"] = PERSON1
jkg_quotes["TODO_FUNNY_QUOTE2"] = PERSON2
jkg_quotes["TODO_FUNNY_QUOTE3"] = PERSON3
jkg_quotes["TODO_FUNNY_QUOTE4"] = PERSON4
jkg_quotes["TODO_FUNNY_QUOTE5"] = PERSON1

# I don't know either why I made a country quiz!?
countries = {
    "Afghanistan": "Kabul",
    "Aland Islands": "Mariehamn",
    "Albania": "Tirana",
    "Algeria": "Algiers",        
    "American Samoa": "Pago Pago",
    "Andorra": "Andorra la Vella",
    "Angola": "Luanda",
    "Anguilla": "The Valley",
    "Antarctica": "",
    "Antigua and Barbuda": "St. John's",
    "Argentina": "Buenos Aires",
    "Armenia": "Yerevan",
    "Aruba": "Oranjestad",
    "Australia": "Canberra",
    "Austria": "Vienna",
    "Azerbaijan": "Baku",
    "Bahamas": "Nassau",
    "Bahrain": "Manama",
    "Bangladesh": "Dhaka",
    "Barbados": "Bridgetown",
    "Belarus": "Minsk",
    "Belgium": "Brussels",
    "Belize": "Belmopan",
    "Benin": "Porto-Novo",
    "Bermuda": "Hamilton",
    "Bhutan": "Thimphu",
    "Bolivia": "Sucre",
    "Bonaire, Saint Eustatius and Saba ": "",
    "Bosnia and Herzegovina": "Sarajevo",
    "Botswana": "Gaborone",
    "Bouvet Island": "",
    "Brazil": "Brasilia",
    "British Indian Ocean Territory": "Diego Garcia",
    "British Virgin Islands": "Road Town",
    "Brunei": "Bandar Seri Begawan",
    "Bulgaria": "Sofia",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Bujumbura",
    "Cambodia": "Phnom Penh",
    "Cameroon": "Yaounde",
    "Canada": "Ottawa",
    "Cape Verde": "Praia",
    "Cayman Islands": "George Town",
    "Central African Republic": "Bangui",
    "Chad": "N'Djamena",
    "Chile": "Santiago",
    "China": "Beijing",
    "Christmas Island": "Flying Fish Cove",
    "Cocos (Keeling) Islands": "West Island",
    "Cocos Islands": "West Island",
    "Colombia": "Bogota",
    "Comoros": "Moroni",
    "Cook Islands": "Avarua",
    "Costa Rica": "San Jose",
    "Croatia": "Zagreb",
    "Cuba": "Havana",
    "Curacao": " Willemstad",
    "Cyprus": "Nicosia",
    "Czech Republic": "Prague",
    "Democratic Republic of the Congo": "Kinshasa",
    "Denmark": "Copenhagen",
    "Djibouti": "Djibouti",
    "Dominica": "Roseau",
    "Dominican Republic": "Santo Domingo",
    "Ecuador": "Quito",
    "Egypt": "Cairo",
    "El Salvador": "San Salvador",
    "Equatorial Guinea": "Malabo",
    "Eritrea": "Asmara",
    "Estonia": "Tallinn",
    "Ethiopia": "Addis Ababa",
    "Falkland Islands": "Stanley",
    "Faroe Islands": "Torshavn",
    "Fiji": "Suva",
    "Finland": "Helsinki",
    "France": "Paris",
    "French Polynesia": "Papeete",
    "French Southern Territories": "Port-aux-Francais",
    "Gabon": "Libreville",
    "Gambia": "Banjul",
    "Georgia": "Tbilisi",
    "Germany": "Berlin",
    "Ghana": "Accra",
    "Gibraltar": "Gibraltar",
    "Greece": "Athens",
    "Greenland": "Nuuk",
    "Grenada": "St. George's",
    "Guadeloupe": "Basse-Terre",
    "Guam": "Hagatna",
    "Guatemala": "Guatemala City",
    "Guernsey": "St Peter Port",
    "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau",
    "Guyana": "Georgetown",
    "Haiti": "Port-au-Prince",
    "Heard Island and McDonald Islands": "",
    "Honduras": "Tegucigalpa",
    "Hong Kong": "Hong Kong",
    "Hungary": "Budapest",
    "Iceland": "Reykjavik",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Ireland": "Dublin",
    "Isle of Man": "Douglas, Isle of Man",
    "Israel": "Jerusalem",
    "Italy": "Rome",
    "Ivory Coast": "Yamoussoukro",
    "Jamaica": "Kingston",
    "Japan": "Tokyo",
    "Jersey": "Saint Helier",
    "Jordan": "Amman",
    "Kazakhstan": "Astana",
    "Kenya": "Nairobi",
    "Kiribati": "Tarawa",
    "Kosovo": "Pristina",
    "Kuwait": "Kuwait City",
    "Kyrgyzstan": "Bishkek",
    "Laos": "Vientiane",
    "Latvia": "Riga",
    "Lebanon": "Beirut",
    "Lesotho": "Maseru",
    "Liberia": "Monrovia",
    "Libya": "Tripolis",
    "Liechtenstein": "Vaduz",
    "Lithuania": "Vilnius",
    "Luxembourg": "Luxembourg",
    "Macau": "Macao",
    "Macedonia": "Skopje",
    "Madagascar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Malaysia": "Kuala Lumpur",
    "Maldives": "Male",
    "Mali": "Bamako",
    "Malta": "Valletta",
    "Marshall Islands": "Majuro",
    "Martinique": "Fort-de-France",
    "Mauritania": "Nouakchott",
    "Mauritius": "Port Louis",
    "Mayotte": "Mamoudzou",
    "Mexico": "Mexico City",
    "Micronesia": "Palikir",
    "Moldova": "Chisinau",
    "Monaco": "Monaco",
    "Mongolia": "Ulan Bator",
    "Montenegro": "Podgorica",
    "Montserrat": "Plymouth",
    "Morocco": "Rabat",
    "Mozambique": "Maputo",
    "Myanmar": "Nay Pyi Taw",
    "Namibia": "Windhoek",
    "Nauru": "Yaren",
    "Nepal": "Kathmandu",
    "Netherlands": "Amsterdam",
    "New Caledonia": "Noumea",
    "New Zealand": "Wellington",
    "Nicaragua": "Managua",
    "Niger": "Niamey",
    "Nigeria": "Abuja",
    "Niue": "Alofi",
    "Norfolk Island": "Kingston",
    "North Korea": "Pyongyang",
    "Northern Mariana Islands": "Saipan",
    "Norway": "Oslo",
    "Oman": "Muscat",
    "Pakistan": "Islamabad",
    "Palau": "Melekeok",
    "Palestinian Territory": "East Jerusalem",
    "Panama": "Panama City",
    "Papua New Guinea": "Port Moresby",
    "Paraguay": "Asuncion",
    "Peru": "Lima",
    "Philippines": "Manila",
    "Pitcairn": "Adamstown",
    "Poland": "Warsaw",
    "Portugal": "Lisbon",
    "Puerto Rico": "San Juan",
    "Qatar": "Doha",
    "Republic of the Congo": "Brazzaville",
    "Romania": "Bucharest",
    "Russia": "Moscow",
    "Rwanda": "Kigali",
    "Réunion": "Saint-Denis",
    "Saint Barthelemy": "Gustavia",
    "Saint Helena": "Jamestown",
    "Saint Kitts and Nevis": "Basseterre",
    "Saint Lucia": "Castries",
    "Saint Martin": "Marigot",
    "Saint Pierre and Miquelon": "Saint-Pierre",
    "Saint Vincent and the Grenadines": "Kingstown",
    "Samoa": "Apia",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Sao Tome",
    "Saudi Arabia": "Riyadh",
    "Senegal": "Dakar",
    "Serbia": "Belgrade",
    "Seychelles": "Victoria",
    "Sierra Leone": "Freetown",
    "Singapore": "Singapur",
    "Sint Maarten": "Philipsburg",
    "Slovakia": "Bratislava",
    "Slovenia": "Ljubljana",
    "Solomon Islands": "Honiara",
    "Somalia": "Mogadishu",
    "South Africa": "Pretoria",
    "South Georgia and the South Sandwich Islands": "Grytviken",
    "South Korea": "Seoul",
    "South Sudan": "Juba",
    "Spain": "Madrid",
    "Sri Lanka": "Colombo",
    "Sudan": "Khartoum",
    "Suriname": "Paramaribo",
    "Svalbard and Jan Mayen": "Longyearbyen",
    "Swaziland": "Mbabane",
    "Sweden": "Stockholm",
    "Switzerland": "Berne",
    "Syria": "Damascus",
    "Taiwan": "Taipei",
    "Tajikistan": "Dushanbe",
    "Tanzania": "Dodoma",
    "Thailand": "Bangkok",
    "Timor-Leste": "Dili",
    "Togo": "Lome",
    "Tokelau": "",
    "Tonga": "Nuku'alofa",
    "Trinidad and Tobago": "Port of Spain",
    "Tunisia": "Tunis",
    "Turkey": "Ankara",
    "Turkmenistan": "Ashgabat",
    "Turks and Caicos Islands": "Cockburn Town",
    "Tuvalu": "Funafuti",
    "U.S. Virgin Islands": "Charlotte Amalie",
    "Uganda": "Kampala",
    "Ukraine": "Kiev",
    "United Arab Emirates": "Abu Dhabi",
    "United Kingdom": "London",
    "United States": "Washington",
    "United States Minor Outlying Islands": "",
    "Uruguay": "Montevideo",
    "Uzbekistan": "Tashkent",
    "Vanuatu": "Port Vila",
    "Vatican": "Vatican City",
    "Vatican City State (Holy See)": "Vatican City",
    "Venezuela": "Caracas",
    "Vietnam": "Hanoi",
    "Wallis and Futuna": "Mata Utu",
    "Western Sahara": "El-Aaiun",
    "Yemen": "Sanaa",
    "Zambia": "Lusaka",
    "Zimbabwe": "Harare"}
